/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.util.Calendar;
import java.util.Random;
import java.text.SimpleDateFormat;
import java.awt.Color;

import java.util.*;
import java.awt.*;
import java.text.*;

/**
 *
 * @author Gaurav Chauhan
 */
public class traintickers extends javax.swing.JFrame {

    /**
     * Creates new form traintickers
     */
    public traintickers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Std = new javax.swing.JRadioButton();
        economy = new javax.swing.JRadioButton();
        firstclass = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Single = new javax.swing.JRadioButton();
        Return = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Adult = new javax.swing.JRadioButton();
        Child = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Tax = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        C = new javax.swing.JLabel();
        From1 = new javax.swing.JLabel();
        From = new javax.swing.JLabel();
        TicketNo1 = new javax.swing.JLabel();
        TicketNo = new javax.swing.JLabel();
        To1 = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Route = new javax.swing.JLabel();
        Time1 = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("   Train Ticketing System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Std.setText("Standard");

        economy.setText("Economy");

        firstclass.setText("First Class");
        firstclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstclassActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("Class");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("ticket type");

        Single.setText("Single");
        Single.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SingleActionPerformed(evt);
            }
        });

        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Adult");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("Child");

        Adult.setText("Yes");

        Child.setText("Yes");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Destination");

        cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delhi", "Haryana", "punjab", "srinagar" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Std)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(Single))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Adult))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Child)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(economy)
                                .addGap(18, 18, 18)
                                .addComponent(Return)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)))
                        .addGap(29, 29, 29))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(firstclass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Std)
                        .addComponent(Single)
                        .addComponent(Adult))
                    .addComponent(Child))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(economy)
                    .addComponent(Return)
                    .addComponent(jLabel7))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(firstclass))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Sub Total");

        SubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel10.setText("Tax");

        Tax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("Total");

        Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Exit");
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton2.setText("Total");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                        .addComponent(Tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(SubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel17.setText("Class");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel18.setText("Ticket");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel19.setText("Adult");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel20.setText("child");

        Class.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Type.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        A.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        C.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        From1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        From1.setText("From");

        From.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TicketNo1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        TicketNo1.setText("Ticket No");

        TicketNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        To1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        To1.setText("TO");

        To.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel31.setText("Price");

        Price.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Date1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Date1.setText("Date");

        Date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel35.setText("Route");

        Route.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Time1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Time1.setText("Time");

        Time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(A, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(From1)
                            .addComponent(To1)
                            .addComponent(Date1)
                            .addComponent(Time1))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(From, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Route, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TicketNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel31)
                            .addComponent(TicketNo1)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Class, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(A, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(TicketNo1)
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TicketNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(From, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(From1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31)
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(To1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Date1)
                    .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Route, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Time1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstclassActionPerformed

    private void SingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SingleActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.getContentPane().setBackground(Color.black);
    }//GEN-LAST:event_formWindowActivated

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your han9dling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Calendar Timer = Calendar.getInstance();
        Timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:MM:SS");
        Time.setText(tTime.format(Timer.getTime()));
        
         SimpleDateFormat Tdate = new SimpleDateFormat("HH:MM:YYYY");
         Date.setText(Tdate.format(Timer.getTime()));
         From.setText("Delhi");
         To.setText((String) cb.getSelectedItem()+" " );
         int num1;
         String q1 ="";
         
         num1 = 1325+(int)(Math.random()*4238);
         q1 += num1 + 1325;
        TicketNo.setText(q1);
        Route.setText("any");
        
        
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        double MilesK8 = 25;
        double MilesK12 = 30;
        double MilesK20 = 40;
        double MilesK30 = 55; 
        double tax =20;
        double totalcost, eco =4, fclass =5;
        if ((Std.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK8+totalcost);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
        else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK8+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
       else if ((Std.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8) / 100;
            String sTax = String.format("Rs%.2f",totalcost - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK8+totalcost - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK8 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK8+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
        else if ((Std.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK12+totalcost);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
         else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK12+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
        else if ((Std.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12) / 100;
            String sTax = String.format("Rs%.2f",totalcost - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK12+totalcost - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK12 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK12+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
         else if ((Std.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK20+totalcost);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
           else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK20+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
         else if ((Std.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20) / 100;
            String sTax = String.format("Rs%.2f",totalcost - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK20+totalcost - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
          else if 
        
                ((Std.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK20 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK20+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Std");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
          else if ((economy.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * (MilesK8 + eco) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8+ eco);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK8+totalcost + eco);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
        else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK8+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
       else if ((economy.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8) / 100;
            String sTax = String.format("Rs%.2f",(totalcost +eco) - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK8+totalcost + eco) - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK8 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK8+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
         else if ((economy.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Punjab"))
        {
            totalcost = (tax * (MilesK12 + eco) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12+ eco);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK12+totalcost + eco);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
        else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK12+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
       else if ((economy.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Punjab"))
        {
            totalcost = (tax * MilesK12) / 100;
            String sTax = String.format("Rs%.2f",(totalcost +eco) - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK12+totalcost + eco) - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK12 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK12+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
         else if ((economy.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * (MilesK20 + eco) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20+ eco);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK20+totalcost + eco);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
        else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK20+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
       else if ((economy.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20) / 100;
            String sTax = String.format("Rs%.2f",(totalcost +eco) - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK20+totalcost + eco) - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((economy.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK20 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK20+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("Economy");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
         else if ((firstclass.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * (MilesK8 + fclass) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8 + fclass);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK8+totalcost + fclass);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
        else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK8+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
       else if ((firstclass.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8+fclass) / 100;
            String sTax = String.format("Rs%.2f",(totalcost+fclass) - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK8+fclass);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK8+totalcost+fclass) - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("Haryana"))
        {
            totalcost = (tax * MilesK8 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK8 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK8+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
        else if ((firstclass.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * (MilesK12+fclass) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12+fclass);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK12+totalcost+fclass);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
         else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK12+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
        else if ((firstclass.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * (MilesK12+fclass) / 100);
            String sTax = String.format("Rs%.2f",(totalcost+fclass) - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK12);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK12+totalcost+fclass) - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
         else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("punjab"))
        {
            totalcost = (tax * MilesK12 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK12 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK12+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
         else if ((firstclass.isSelected())&& (Single.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * (MilesK20 +fclass ) / 100);
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20+fclass);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK20+totalcost+fclass);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("one");
            C.setText("nill");
        }
           else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Adult.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20 *2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",(MilesK20+totalcost)*2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("one");
            C.setText("nill");
        }
         else if ((firstclass.isSelected())&& (Single.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * (MilesK20+fclass) / 100);
            String sTax = String.format("Rs%.2f",totalcost - 2);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",MilesK20+fclass);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",MilesK20+totalcost+fclass - 2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("one way");
            A.setText("nill");
            C.setText("one");
        }
          else if 
        
                ((firstclass.isSelected())&& (Return.isSelected())&& (Child.isSelected())  && cb.getSelectedItem().equals("srinagar"))
        {
            totalcost = (tax * MilesK20 *2) / 100;
            String sTax = String.format("Rs%.2f",totalcost);
            Tax.setText(sTax);
            String Subtotal = String.format("Rs%.2f",(MilesK20 *2)-2);
            SubTotal.setText(Subtotal);
            String total = String.format("Rs%.2f",((MilesK20+totalcost)*2)-2);
            Total.setText(total);
            Price.setText(total);
            Class.setText("firstclass");
            Type.setText("Return");
            A.setText("nill");
            C.setText("one");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(traintickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(traintickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(traintickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(traintickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new traintickers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JRadioButton Adult;
    private javax.swing.JLabel C;
    private javax.swing.JRadioButton Child;
    private javax.swing.JLabel Class;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Date1;
    private javax.swing.JLabel From;
    private javax.swing.JLabel From1;
    private javax.swing.JLabel Price;
    private javax.swing.JRadioButton Return;
    private javax.swing.JLabel Route;
    private javax.swing.JRadioButton Single;
    private javax.swing.JRadioButton Std;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Tax;
    private javax.swing.JLabel TicketNo;
    private javax.swing.JLabel TicketNo1;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Time1;
    private javax.swing.JLabel To;
    private javax.swing.JLabel To1;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel Type;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JRadioButton economy;
    private javax.swing.JRadioButton firstclass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
